### ISSUE TITLE
Missing game from the list

### ISSUE THREAD

**Issue by Xakkar** [mkalam-alami/ludumdare-feedback-friends#41]
Hello. Today's missing our game from list Feedback friends: http://ludumdare.com/compo/ludum-dare-36/?action=preview&uid=76807

**Comment by mkalam-alami** [comment]
Hi! I'm sorry but we actually removed your game from Feedback Friends as most of the given comments were low effort: about 40 of them were just "Cool game!" or "Nice game!" :disappointed: 

Since you already got a lot of feedback we decided to make room for more constructive commenters, I hope you don't mind.

**Comment by ttencate** [comment]
@mkalam-alami Do you think we should maybe keep at least the entry pages visible in such cases?

**Comment by Xakkar** [comment]
Hi. We don't know that feedback should be more constructive. Promise that in the future our comments will be more constructive. Please return the game to the list :-)

**Comment by mkalam-alami** [comment]
@ttencate Like searchable but not in the list? Why not I can look into it.

@Xakkar Ok, just please try to be more constructive, you probably wouldn't like it if all the comments you got were 2 words long! Your entry should be back within 30mn :)

**Comment by Xakkar** [comment]
@mkalam-alami Thanks)
