### ISSUE TITLE
Question: Where are you getting the list of games from?

### ISSUE THREAD

**Issue by balohmatevz** [mkalam-alami/ludumdare-feedback-friends#50]
Which page on the ldjam.com site contains a list of entries? Is there anything similar to the misc_links page from the old site?

**Comment by mkalam-alami** [comment]
LDJam actually loads all its contents through AJAX, so that means there's a JSON API we can also use to grab games info. Much easier that before ;)

> http://api.ldjam.com/vx/node/feed/9405/parent+superparent/item/game?limit=25&offset=0

[Link to relevant sources](https://github.com/mkalam-alami/ludumdare-feedback-friends/blob/master/includes/ludumdare.php#L12)

See also the same file to check how exactly I get comments & user information (requires additional requests).

**Comment by balohmatevz** [comment]
Ah! I'm hoping there will be an API which will include the number of received votes for each game. I'd like to get Rescue Chicken up and running too. 

Granted considering voting isn't done yet, it's reasonable for that to not yet be in an API.

**Comment by mkalam-alami** [comment]
There's a good chance it will be included when voting is launched yes. If it does, I suspect this kind of info will appear in the "meta" section of nodes (see e.g. http://api.ldjam.com/vx/node/get/28468).

**Comment by balohmatevz** [comment]
Let's hope! Thanks for the answer 👍
